//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Velman.rc
//
#define IDR_MAINFRAME                   2
#define IDR_VELMANTYPE                  3
#define IDD_ABOUTBOX                    100
#define IDD_STARTUP                     102
#define ID_MODELCHOICE_DLGBACKBUTTON    102
#define IDD_PROJ_SETTINGS               103
#define ID_FINETUNE_DLGBACKBUTTON       103
#define IDD_NEWPROJ_1                   104
#define ID_LISTOFMO_DONEBUTTON          104
#define IDB_SPLASH                      105
#define IDD_SECRET_ONHAVELKA            106
#define IDB_SPLASH_BACKUP               106
#define ID_SEISMICMAP_DONEBUTTON        107
#define ID_SEISMICMAP_SHOWZNON          108
#define ID_CONTOURVIEW_SHOWFAULTS       109
#define ID_CONTOURVIEW_SHOWSHOTPOINTS   110
#define ID_LISTOFTIE_DUMPBUTTON         111
#define ID_GRIDMAP_OPTIONS              112
#define ID_CONTOURVIEW_SHOWWELLS        113
#define ID_ALLRESI_DONEBUTTON           114
#define IDD_ConfigForm_DIALOG           116
#define IDD_PROJ_GUIDE_DLG              117
#define IDI_PROJ_GUIDE                  118
#define IDD_CREATE_PROJ_PROGRESS        119
#define IDD_RMSIMPORT1                  126
#define IDD_FILTERMANAGEMENT            128
#define IDD_RMS_COORDCONV               129
#define IDD_RMS_COORDCONV2              130
#define IDD_IMPORT_PROGRESS             131
#define IDD_PROGRESS                    131
#define IDR_ACCELERATOR1                132
#define IDD_WELLHORIZ_TIMEGRID_MAP      134
#define IDD_MAPPING_ERROR               135
#define IDD_NEWPROJ_2                   136
#define IDD_MODEL_CHOOSELAYER           138
#define IDD_MODELCHOICE                 140
#define IDD_FINETUNE_MODEL              141
#define IDD_EDITWELL                    142
#define IDD_CHANGE_WEIGHTS              145
#define IDD_NUMERIC_RESIDUES            146
#define IDD_FINETUNE_QUICKHELP          147
#define IDD_RMSIMPORT_2DSUPPFILE        149
#define IDI_ICON1                       156
#define IDD_TIMEGRIDFILTER_OPTIONS      158
#define IDD_SMOOTHGRID_OPTIONS          158
#define IDD_BEFORE_PROCESSIMPORTEDDATA  159
#define IDD_DIALOG1                     162
#define IDD_CONTOUR_SETTINGS            165
#define IDD_TIMEGRID_CONTOUR_DLG        168
#define IDD_CHOOSE_ANY_GRID             170
#define IDD_CHOOSE_ANY_GRID_MULT        171
#define IDD_GRID_ARITHMETIC             172
#define IDD_NEWPROJ_3                   175
#define IDD_RENAME_GRID                 176
#define IDD_CREATE_CONSTGRID            177
#define IDD_IMPORT_GRID                 178
#define IDD_DEFINE_HORIZONS             180
#define IDD_SPECTR_ANALYSIS             183
#define IDD_GRIDIMPORT                  184
#define IDD_DESIGNATE_GRID              186
#define IDD_FFT_DIRECTION               189
#define IDD_GRID_STATISTICS             190
#define IDD_TIEDIFF_TABLE               191
#define IDD_WELLTABLES                  191
#define IDD_TIMEGRIDIMP_ERROR           193
#define IDB_SPLASHSCREEN                196
#define IDD_GRID_DIRECTORY              197
#define IDD_HOWTO_AUTOCORR              200
#define IDD_CREATEPROJDIR               201
#define IDD_LIMIT_GRID                  202
#define IDD_DIALOG2                     205
#define IDD_DIALOG3                     206
#define IDD_HOWTOTIE                    207
#define IDD_GRIDANNOTATE                209
#define IDD_SMOOTH_MOVINGWND            210
#define IDD_GRIDDATABASE_LIST           211
#define IDD_EXTEND_LICENSE              212
#define IDD_SECONDARYDEPTHCONV_OPT      213
#define IDD_DEPTHCONV_TIMESLICE         214
#define IDD_RESULTS_RMSTESTIMPORT       215
#define IDD_REBUILD_SETTINGS            216
#define IDD_LOGFILEVIEW                 217
#define IDD_TIMECONVERT                 219
#define IDD_WELLFORECAST                220
#define IDD_TIMEIMPORT_WHATTOTIE        221
#define IDI_STOPSIGN                    222
#define IDD_FINETUNE_CUSTOMFIT_PAGE     225
#define IDD_FINETUNE_MISC_PAGE          226
#define IDD_FINETUNE_QUICKHELP1_PAGE    227
#define IDD_FINETUNE_QUICKHELP2_PAGE    228
#define IDD_FINETUNE_FIT_PAGE           230
#define IDD_FINETUNE_WEIGHTS_PAGE       231
#define IDI_FINETUNE                    232
#define IDD_WARN_OTHERMODEL             237
#define IDD_FINETUNE_RESIDUALS_PAGE     238
#define IDD_IMRDIALOGUE                 241
#define IDD_GCNEWPROJ                   242
#define IDD_RAYTRACE_PROPS              248
#define IDD_GRID_OVERWRITENULL          249
#define IDD_GRIDEXPORT                  250
#define IDD_OPEN_FILE_BRWS              257
#define IDD_IMP_WELL_HOR_DATA           262
#define IDD_DIALOG4                     263
#define IDD_CHOOSE_ANY_WELL             263
#define IDD_DIALOG5                     269
#define IDC_OPENPROJECT                 1000
#define IDC_RADIO1                      1002
#define IDC_NEWPROJBUTTON               1002
#define IDC_OPENPROJ_BUTTON             1002
#define IDC_MODELCHOICE_LIN1            1002
#define IDC_RADIO2                      1003
#define IDC_NEWPROJ_BUTTON              1003
#define IDC_MODELCHOICE_FUNC1           1003
#define IDC_ARITH_INPUT1                1003
#define IDC_NEWPROG_UNITS               1003
#define IDC_NEWPROJ_GRIDFILETYPE        1003
#define IDC_DESGRID_HORS                1003
#define IDC_RADIO3                      1004
#define IDC_FILTERNAMELIST              1004
#define IDC_LISTOFINSTALLEDFILTERS      1004
#define IDC_WELLTIME_GRIDLIST           1004
#define IDC_MAPERR_LIST                 1004
#define IDC_CHOOSE_MODELLIST            1004
#define IDC_CHOOSEEDIT_LIST             1004
#define IDC_NUMRES_LIST1                1004
#define IDC_RMS2DSUPP_GRIDLIST          1004
#define IDC_ARITH_INPUT2                1004
#define IDC_DEFHOR_LIST                 1004
#define IDC_NEWPROJ_GRIDNAMESPREVIEW    1004
#define IDC_TIMPERR_LIST                1004
#define IDC_GRIDLIMIT_INPUT1            1004
#define IDC_GDB_TABLE                   1004
#define IDC_TESTIMPORT_LIST             1004
#define IDC_DESGRID_LIST                1004
#define IDC_TCD_LIST                    1004
#define IDC_WELLFC_LIST                 1004
#define IDC_NEWPROJ_1                   1005
#define IDC_WELLTIME_WELLLIST           1005
#define IDC_NUMRES_LIST2                1005
#define IDC_ARITH_RADIO3                1005
#define IDC_GRIDLIMIT_INPUT2            1005
#define IDC_CONTSET_FEWLABELS           1005
#define IDC_NUMRES_LIST3                1006
#define IDC_WELLTIME_FAULTGRIDLIST      1006
#define IDC_CONTSET_NORMALLABELS        1006
#define IDC_NUMRES_LIST4                1007
#define IDC_CONTSET_MANYLABELS          1007
#define IDC_BUTTON1                     1010
#define IDC_NEWPROJ_OPTIONS             1010
#define IDC_COORD_NOCONV                1010
#define IDC_WELLTIME_ASSIGN             1010
#define IDC_FINETUNE_OTHERMODEL         1010
#define IDC_CHGWEIGHT_DEFAULTS          1010
#define IDC_MODELCHOICE_MODEBTN         1010
#define IDC_PROCESSDATA_FILTEROPT       1010
#define IDC_STARTUP_FILE4               1010
#define IDC_DEFHOR_REMOVE               1010
#define IDC_RETRYBTN                    1010
#define IDC_NEWPROJ1_NEWDIR             1010
#define IDC_TCD_READFROMFILE            1010
#define IDC_WELLFC_STD                  1010
#define IDC_FINETUNE_DISPLAYCUSTOMFIT   1010
#define IDC_CONTSET_LABELSMALLER        1010
#define IDC_SMOOTHOPT_UPDATE            1010
#define IDC_BUTTONTD                    1010
#define IDC_CONTSET_CHANGETEXTCOL       1011
#define IDC_STARTUP_FILE1               1011
#define IDC_BUTTON3                     1011
#define IDC_BUTTONSINGLE                1011
#define IDC_COMBO_NEWPROJDRIVE          1012
#define IDC_STARTUP_FILE2               1012
#define IDC_CONTSET_LABELLARGER         1012
#define IDC_STARTUP_FILE3               1013
#define IDC_LIST_NEWPROJDIR             1014
#define IDC_WHATNOW_TEXT                1015
#define IDC_LIST_NEWPROJDIRFILES        1015
#define IDC_TARGET_PATH_TEXT            1016
#define IDC_NEWPROJ_CURRENT             1017
#define IDC_CHECK1                      1018
#define IDC_WELLTIME_TIEGRIDS           1018
#define IDC_SPECANAL_REBUILD            1018
#define IDC_DCOPT_REBUILD               1018
#define IDC_FINETUNE_SHOWWELLLABELS     1018
#define IDC_REBUILDSETTINGS_DOALL       1018
#define IDC_TIE                         1018
#define IDC_WELLTIME_USEFAULTS          1018
#define IDC_CONTSET_SHOWLABELS          1018
#define IDC_FINETUNE_USECUSTOMFIT       1018
#define IDC_WARNOTHERMODEL_RETAINWEIGHTS 1018
#define IDC_RESIDUALS_INZONLY           1018
#define IDC_RAYTRACE_PROPS_XYOFFSET     1018
#define IDC_GRAPHICVIEW                 1018
#define IDC_CHECK2                      1019
#define IDC_CONTSET_USESHADING          1019
#define IDC_FINETUNE_KEEPRESIDUALS      1019
#define IDC_RESIDUALS_TOTALDESELECTION  1019
#define IDC_RAYTRACE_PROPS_ANGLEGRIDS   1019
#define IDC_PRIMARY                     1019
#define IDC_CHECK3                      1020
#define IDC_MODELCHOICE_FUNC2           1020
#define IDC_WELLTIME_NORMGRAD           1020
#define IDC_FINETUNE_SHOWGRID           1020
#define IDC_CONTSET_SHOWFAULTS          1020
#define IDC_RAYTRACE_PROPS_DEPTHDIFF    1020
#define IDC_ADDFILTER                   1021
#define IDC_MODELCHOICE_LIN2            1021
#define IDC_FINETUNE_SHOWALLWELLS       1021
#define IDC_MODELCHOICE_QUAD2           1022
#define IDC_COORD_LOCX1                 1023
#define IDC_COORD_LOCY1                 1024
#define IDC_MODELCHOICE_FUNC3           1024
#define IDC_COORD_GLBX1                 1025
#define IDC_MODELCHOICE_LIN3            1025
#define IDC_COORD_GLBY1                 1026
#define IDC_MODELCHOICE_QUAD3           1026
#define IDC_COORD_LOCX2                 1027
#define IDC_COORD_LOCY2                 1028
#define IDC_MODELCHOICE_FUNC4           1028
#define IDC_COORD_GLBX2                 1029
#define IDC_MODELCHOICE_LIN4            1029
#define IDC_COORD_GLBY2                 1030
#define IDC_MODELCHOICE_QUAD4           1030
#define IDC_COORD2_LIN1                 1031
#define IDC_COORD2_SP1                  1032
#define IDC_COORD2_GLBX1                1033
#define IDC_COORD2_GLBY1                1034
#define IDC_COORD2_LIN2                 1035
#define IDC_RMSIMPORT_CURRENT           1035
#define IDC_COORD2_SP2                  1036
#define IDC_RMSIMPORT_CURRENT2          1036
#define IDC_COORD2_GLBX2                1037
#define IDC_INFO_SELECTED_FILTER        1037
#define IDC_COORD2_GLBY2                1038
#define IDC_WELLTIME_ASSIGNLIST         1038
#define IDC_COORD2_LIN3                 1039
#define IDC_WELLTIME_DELETEENTRY        1039
#define IDC_COORD2_SP3                  1040
#define IDC_TARGET_PATH_TEXT2           1040
#define IDC_COORD2_GLBX3                1041
#define IDC_COMBO_NEWPROJDRIVE2         1041
#define IDC_COORD2_GLBY3                1042
#define IDC_LIST_NEWPROJDIR2            1042
#define IDC_FINETUNE_FUNCNAME           1046
#define IDC_FINETUNE_PARNAME1           1047
#define IDC_FINETUNE_PARVAL1            1048
#define IDC_FINETUNE_PARNAME2           1049
#define IDC_FINETUNE_PARVAL2            1050
#define IDC_FINETUNE_EXCLTEXT           1051
#define IDC_FINETUNE_EXCLSCRL           1052
#define IDC_EDITWELL_X                  1053
#define IDC_FINETUNE_FUNCDISTWGT        1053
#define IDC_EDITWELL_Y                  1054
#define IDC_FINETUNE_FITVAL             1054
#define IDC_EDITWELL_DEP                1055
#define IDC_EDITWELL_TIME               1056
#define IDC_EDITWELL_WEIGHT             1057
#define IDC_EDITWELL_EXCL               1058
#define IDC_FINETUNE_CHANGEWEIGHT       1060
#define IDC_CHGWEIGHT_X                 1061
#define IDC_CHGWEIGHT_Y                 1062
#define IDC_MODELCHO_PARNAME1           1064
#define IDC_MODELCHO_PARNAME2           1065
#define IDC_MODELCHO_PARVAL1            1066
#define IDC_MODELCHO_PARVAL2            1067
#define IDC_MODELCHO_PARNAME3           1068
#define IDC_MODELCHOICE_RESIDUALS       1068
#define IDC_MODELCHO_PARVAL3            1069
#define IDC_MODELCHOICE_QUAD1           1069
#define IDC_MODELCHO_PARNAME4           1070
#define IDC_MODELCHO_PARVAL4            1071
#define IDC_CHGWEIGHT_METHOD            1071
#define IDC_FINETUNE_SWITCHVIEWMODE     1071
#define IDC_ARITH_OPERATOR              1071
#define IDC_GRIDIMP_GRIDTYPE            1071
#define IDC_NEWPROG_LOGDETAIL           1071
#define IDC_MODELCHO_PARNAME5           1072
#define IDC_ARITH_EDIT1                 1072
#define IDC_GRIDRENAME_NAME             1072
#define IDC_CONSTGRID_VALUE             1072
#define IDC_DEFHOR_NEWENTRY             1072
#define IDC_CREATEDIR_NAME              1072
#define IDC_CHGWEIGHT_METHOD2           1072
#define IDC_MODELCHO_PARVAL5            1073
#define IDC_ARITH_EDIT2                 1073
#define IDC_TCD_X                       1073
#define IDC_WELLFC_Y                    1073
#define IDC_FINETUNE_CUSTOMFITB         1073
#define IDC_MODELCHO_PARNAME6           1074
#define IDC_CHGWEIGHT_RAD               1074
#define IDC_TCD_Y                       1074
#define IDC_MODELCHO_PARNAME7           1076
#define IDC_MODELCHO_PARVAL7            1077
#define IDC_MODELCHOICE_STATIC          1077
#define IDC_MODELCHO_PARNAME8           1078
#define IDC_NUMRES_CHI1                 1078
#define IDC_MODELCHO_PARVAL8            1079
#define IDC_MODELCHOICE_HIDEDLG         1079
#define IDC_NUMRES_CHI3                 1079
#define IDC_FINETUNE_HIDEME             1080
#define IDC_NUMRES_CHI2                 1080
#define IDC_NUMRES_CHI4                 1081
#define IDC_RMSIMPORT_GENDESCR          1081
#define IDC_FILTERCHOICE_UNIT           1082
#define IDC_TGF_HORZLIST                1083
#define IDC_TGF_APLLYTOALL              1084
#define IDC_TGF_LOWPASSFILT             1085
#define IDC_TGF_TPSRADIUS               1086
#define IDC_TGF_LOWPASSVALUE            1087
#define IDC_TGF_TPSRADVALUE             1088
#define IDC_WELLTIME_HELPTEXT           1089
#define IDC_RMSIMPORT_PROGBAR           1095
#define IDC_EDITWELL_WELLANDLAYER       1098
#define IDC_FINETUNE_ADDBACKALL         1100
#define IDC_CONTSET_TEXTCOLPREVIEW      1104
#define IDC_CONTSET_ZOOMNOTE            1109
#define IDC_CONTZOOM_ZOOMFRAME          1110
#define IDC_CONTSET_SCRL1               1111
#define IDC_CONTSET_SCRLTEXT            1112
#define IDC_CHOOSEGRID_LIST             1113
#define IDC_APPEARANCEBLURB2            1113
#define IDC_CHOOSEGRID_WHATSORT         1114
#define IDC_RADIO4                      1117
#define IDC_SCOPDLG_RADIO3              1117
#define IDC_AFTERTIE4                   1117
#define IDC_CONTSET_PAL_GREY            1117
#define IDC_ARITH_RADIO4                1118
#define IDC_ARITH_RADIO1                1119
#define IDC_ARITH_RADIO2                1120
#define IDC_DEFHOR_DONE                 1123
#define IDC_SPECANAL_GRAPH              1125
#define IDC_SPECANAL_NUMEXCL            1128
#define IDC_SPECANAL_BTMSLIDER          1132
#define IDC_SPECANAL_INCL               1133
#define IDC_SMOOTHOPT_SCRL              1134
#define IDC_SMOOTHOPT_PREVIEW           1135
#define IDC_SMOOTHOPT_FILTVAL           1136
#define IDC_EDITWELL_NOTE               1137
#define IDC_GRIDIMP_GRIDLIST            1138
#define IDC_GRIDIMP_FAULTGRIDLIST       1139
#define IDC_FFTDIR_BUTTON1              1142
#define IDC_GRIDSTAT_XEXT               1143
#define IDC_GRIDSTAT_YEXT               1144
#define IDC_GRIDSTAT_MINMAX             1145
#define IDC_GRIDSTAT_AVG                1146
#define IDC_CONTSET_MAXVAL              1146
#define IDC_CONTSET_MINVAL              1147
#define IDC_GRIDSTAT_GRIDSIZE           1147
#define IDC_CONTSET_MAXCOL              1148
#define IDC_GRIDSTAT_FAULTS             1148
#define IDC_CONTSET_MINCOL              1149
#define IDC_TIMPERR_RECC                1150
#define IDC_AUTOCORRECT_BTN             1151
#define IDC_SMOOTHOPT_XMAX              1157
#define IDC_SMOOTHOPT_YMAX              1158
#define IDC_ARITH_RESULTNAME            1158
#define IDC_NUMRES_PAR1                 1159
#define IDC_NUMRES_PAR2                 1160
#define IDC_NUMRES_PAR3                 1161
#define IDC_NUMRES_PAR4                 1162
#define IDC_NUMRES_FRAME1               1163
#define IDC_NUMRES_FRAME2               1164
#define IDC_NUMRES_FRAME3               1165
#define IDC_NUMRES_FRAME4               1166
#define IDC_CREATEDIR_BASEPATH          1167
#define IDC_HOWTOCORRECT_RADIO2         1168
#define IDC_HOWTOCORRECT_RADIO3         1169
#define IDC_HOWTOCORRECT_RADIO4         1170
#define IDC_CHGWGT_DOWNTONUMBER         1173
#define IDC_GRIDLIMIT_OUTPUTNAME        1174
#define IDC_CHGWGT_PREVIEW              1176
#define IDC_CHGWGT_DOWNTOSCROLL         1177
#define IDC_COMBO_NEWPROJDRIVE_TEXT     1178
#define IDC_COMBO_NEWPROJDRIVE2_TEXT    1179
#define IDC_SCOPDLG_RADIO1              1182
#define IDC_SCOPDLG_RADIO2              1183
#define IDC_WELLTIME_NORMGRAD_SCROLLBUDDY 1186
#define IDC_WELLTIME_NORMGRAD_SCROLLBLURP 1187
#define IDC_WELLTIME_NORMGRAD_SCROLL    1188
#define IDC_HOWTOTIE_NORMGRAD           1189
#define IDC_HOWTOTIE_NORMGRAD_SCROLLBLURP 1190
#define IDC_HOWTOTIE_NORMGRAD_SCROLL    1191
#define IDC_HOWTOTIE_NORMGRAD_SCROLLBUDDY 1192
#define IDC_FINETUNE_NORMGRAD           1193
#define IDC_FINETUNE_NORMGRAD_SCROLLBLURP 1194
#define IDC_FINETUNE_NORMGRAD_SCROLL    1195
#define IDC_FINETUNE_NORMGRAD_SCROLLBUDDY 1196
#define IDC_FINETUNE_TEXT1              1197
#define IDC_FINETUNE_TEXT2              1198
#define IDC_FINETUNE_TEXT3              1199
#define IDC_FINETUNE_TEXT4              1200
#define IDC_HOWTOCORRECT_RADIO1         1201
#define IDC_NEWPROJ_GRIDFILETYPEBLURB   1202
#define IDC_WNDSMOOTH_SLIDER            1203
#define IDC_WNDSMOOTH_SIZEPREVIEW       1204
#define IDC_GRIDSTAT_DELTAX             1205
#define IDC_GRIDSTAT_DELTAY             1206
#define IDC_LICENSE_LICTYPE             1208
#define IDC_LICENSE_LICDATE             1209
#define IDC_LICENSE_VELCUBE             1210
#define IDC_GRIDDATABASE_RADIO1         1211
#define IDC_GRIDDATABASE_RADIO2         1212
#define IDC_DCOPT_PREVIEW               1213
#define IDC_DCOPT_LINEAR                1214
#define IDC_DCOPT_CUBIC                 1215
#define IDC_DCOPT_CONTINUE              1216
#define IDC_DCOPT_DECREASE              1217
#define IDC_DCOPT_DECREASEBY            1218
#define IDC_DCTIMESLICE_VALUE           1218
#define IDC_TESTIMPORT_COORDNOTE        1219
#define IDC_REBUILDSETTINGS_NUMBER      1220
#define IDC_PROJECTLOG_TEXT             1221
#define IDC_DCOPT_CONST                 1222
#define IDC_TCD_D                       1223
#define IDC_TCD_NAME                    1224
#define IDC_TCD_WRITETOFILE             1225
#define IDC_TCD_TIMECONV                1226
#define IDC_TCD_DELETE                  1227
#define IDC_WELLFC_X                    1230
#define IDC_WELLFC_RESULT               1234
#define IDC_AFTERTIE1                   1235
#define IDC_AFTERTIE2                   1236
#define IDC_AFTERTIE3                   1237
#define IDC_STATIC_RETAINBLURB          1238
#define IDC_STATIC_RETAINFRAME          1239
#define IDC_TCD_DELETEALL               1240
#define IDC_CONTSET_LABELSIZEPREVIEW    1242
#define IDC_FINETUNE_ADDRESID           1243
#define IDC_FINETUNE_SLOPEWARN          1244
#define IDC_FINETUNE_SLOPEWARN2         1245
#define IDC_BUTTON2                     1247
#define IDC_SAVE                        1247
#define IDC_BUTTONSV                    1247
#define IDC_BUTTONUP                    1247
#define IDC_FINETUNE_DOEDIT             1248
#define IDC_FINETUNE_CUSTOMFITA         1250
#define IDC_FINETUNE_CUSTOMFITANAME     1251
#define IDC_FINETUNE_CUSTOMFITBNAME     1252
#define IDC_CUSTOMFITFRAME              1254
#define IDC_FINETUNE_CUSTOMFITBLURB     1255
#define IDC_CONTSET_SHOWWELLS           1259
#define IDC_CONTSET_SHOWSHOTPOINTS      1260
#define IDC_CONTSET_NUMLEVELS           1263
#define IDC_CONTSET_NUMLEVS_NONE        1263
#define IDC_OTHERELEMENTSFRAME          1264
#define IDC_ABOUTBOX_VERSION            1265
#define IDC_SMOOTHOPT_0                 1267
#define IDC_SMOOTHOPT_95                1268
#define IDC_SMOOTHOPT_HOWTO             1271
#define IDC_NEWPROJ_EDIT_DIR            1273
#define IDC_APPEARANCEBLURB1            1275
#define IDC_APPEARANCEBLURB3            1276
#define IDC_RESIDUAL_NORMGRAD_SCROLLBUDDY 1277
#define IDC_RESIDUAL_ADDRESID           1278
#define IDC_RESIDUAL_MULTRESID          1279
#define IDC_RESIDUAL_NOTIEWARN          1280
#define IDC_TIMELIST                    1286
#define IDC_SMOOTHSIZE                  1288
#define IDC_SIZETEXT                    1289
#define IDC_NEWPROJ2_EDITDIR            1290
#define IDC_EDIT1                       1292
#define IDC_OVERWRITENULL_VALUE         1292
#define IDC_FILENAME_EDIT               1292
#define IDC_EDITFROM                    1292
#define IDC_EDIT2                       1293
#define IDC_EDITTO                      1293
#define IDC_COMBO1                      1295
#define IDC_COMBO2                      1296
#define IDC_REBUILD_DEPTH               1297
#define IDC_LICENSE_RAYTRACE            1298
#define IDC_CONTSET_PAL_RAIN            1304
#define IDC_CONTSET_NUMLEVS_LOW         1306
#define IDC_CONTSET_NUMLEVS_NORM        1307
#define IDC_CONTSET_NUMLEVS_HIGH        1308
#define IDC_LABEL_DENSITY_TXT           1309
#define IDC_CONTSET_PAL_TEXT            1310
#define IDC_RAYTRACE_PROPS_TEXT1        1311
#define IDC_RAYTRACE_PROPS_TIMENULL     1312
#define IDC_RAYTRACE_PROPS_TIMEZERO     1313
#define IDC_RAYTRACE_PROPS_ANGLEGRIDSVERT 1314
#define IDC_RAYTRACE_PROPS_ANGLEGRIDSDIFF 1315
#define IDC_RAYTRACE_PROPS_STOPTEXT1    1316
#define IDC_RAYTRACE_PROPS_LIMITANGLE   1317
#define IDC_RAYTRACE_PROPS_LIMITANGLEDIFF 1321
#define IDC_RAYTRACE_PROPS_STOPRAYONANGLE 1322
#define IDC_RAYTRACE_PROPS_STOPTEXT2    1323
#define IDC_RAYTRACE_PROPS_LIMITANGLETRUEVERT 1324
#define IDC_RAYTRACE_PROPS_AZIMUTH      1325
#define IDC_RAYTRACE_PROPS_REGRIDBINSIZE 1326
#define IDC_RAYTRACE_PROPS_RATIOVALUE   1327
#define IDC_EDITWELL_LABELSIZESCATTER   1328
#define IDC_STATIC2                     1332
#define IDC_OVERWRITE_LIST              1333
#define IDC_CHOOSEEXPORT_LIST           1335
#define IDC_CHOOSEEXPORT_GRIDFILETYPE   1336
#define IDC_STATIC1                     1337
#define IDC_STATIC4                     1338
#define IDC_STATIC3                     1339
#define IDC_STATICL                     1340
#define IDC_STATICR                     1341
#define IDOKnew                         1344
#define IDC_SLASH_TEXT                  1345
#define IDC_RADIO5                      1346
#define IDC_RADIO6                      1347
#define IDC_RADIO7                      1348
#define IDC_RADIO8                      1349
#define IDC_RADIO9                      1350
#define IDC_RADIO10                     1351
#define IDC_RADIO11                     1352
#define IDC_RADIO12                     1353
#define IDC_RADIO13                     1354
#define IDC_RADIO14                     1355
#define IDC_STATIC5                     1356
#define IDC_STATIC6                     1357
#define IDC_STATIC7                     1358
#define IDC_STATICDIR                   1359
#define IDC_SPECANAL_MINMAX             1360
#define IDC_SPECANAL_NULL               1361
#define IDC_LIST1                       1362
#define IDC_LABEL                       1363
#define IDC_RESIDUAL_HYBRID             1364
#define IDC_WELLLIMITS                  1365
#define IDC_GRIDLIMITS                  1366
#define IDC_STATIC8                     1369
#define IDC_STATIC9                     1370
#define IDC_RICHEDIT21                  1371
#define IDC_MFCLINK1                    1374
#define ID_MODEL_CREATEMODEL            32771
#define ID_MODEL_APPLYMODEL             32772
#define ID_HELP_WHATNOW                 32773
#define IDS_WHATNOW0                    32774
#define ID_EXPORT_WELLDATA                 32774
#define IDS_WHATNOW1                    32775
#define ID_IMPORT_IMPORTRMSDATA         32775
#define ID_IMPORT_FILTERMANAGEMENT      32776
#define ID_IMPORT_IMPORTZIMMSDATA       32777
#define ID_PROJECT_TRY                  32779
#define ID_EXPORT_EXPORTZIMSCUBE        32780
#define ID_MODEL_SHOWRESIDUALTABLE      32781
#define ID_MODEL_SHOWLISTOFMODELS       32782
#define ID_IMPORT_IMPORTTIMEDATA        32783
#define ID_MODEL_CLEARALLMODELSDEBUGFUNCTION 32784
#define ID_IMPORT_PROCESSDATA           32785
#define ID_PROCESS_PROCESSTIMEGRIDS     32788
#define ID_PROCESS_PROCESSRMSVELOCITIES 32789
#define ID_PROCESS_DEPTHCONVERSION      32790
#define ID_WELLMODELLING_IMPORTWELLDATA 32791
#define ID_TIMEDATA_CONTOURPLOTOFTIMEGRIDS 32794
#define ID_GRIDS_CONTOURPLOT            32794
#define ID_GRIDS_EXPORT                 32795
#define ID_GRIDS_IMPORT                 32796
#define ID_GRIDS_DELETE                 32797
#define ID_GRIDS_FOURIERTRANSFORM       32798
#define ID_GRIDS_SMOOTH                 32799
#define ID_GRIDS_PATCH                  32800
#define ID_GRIDS_GRIDARITHMETIC         32801
#define ID_GRIDS_RENAME                 32802
#define ID_GRIDS_CREATECONSTANTGRID     32803
#define ID_DEPTHCONVERSION_CREATEDEPTHGRIDS 32804
#define ID_DEPTHCONVERSION_PERFORMVELOCITYANALYSIS 32805
#define ID_WELLSHORIZONS_DEFINEHORIZONS 32806
#define ID_GRIDS_SPECTRUMANALYSIS       32807
#define ID_GRIDS_DUPLICATE              32808
#define ID_GRIDS_DESIGNATE              32809
#define ID_GRIDS_TIETOWELLDATA          32811
#define ID_GRIDTOOLS_STATISTICS         32812
#define ID_SHOWWELLDATATABLEBUTTON      32814
#define ID_WELLSLAYERS_REPAIRWELLDATABASE 32815
#define ID_PROJECT_EXPORT               32817
#define ID_GRIDTOOLS_DIRECTORY          32818
#define ID_GRIDTOOLS_DESIGNATE          32819
#define ID_GRIDTOOLS_LIMIT              32820
#define ID_GRIDTOOLS_SMOOTH             32821
#define ID_PROJECT_VIEWGRIDDATABASE     32822
#define ID_PROJECT_EXTENDLICENSE        32823
#define ID_DEPTHCONVERSION_CONVERTSECONDARYTIMEGRID 32825
#define ID_DEPTHCONVERSION_CONVERTTIMESLICE 32826
#define ID_SEISMICDATA_TESTRMSIMPORT    32828
#define ID_SEISMICDATA_MAPOFSHOTPOINTS  32829
#define ID_DEPTHCONVERSION_VELOCITYCUBE_VELOCITYTIMESLICE 32830
#define ID_PROJECT_VIEWLOGFILE          32831
#define ID_DEPTHCONVERSION_VELOCITYCUBE_CONVERTSINGLEWELLLOCATIONS 32832
#define ID_DEPTHCONVERSION_VELOCITYCUBE_WELLFORECAST 32833
#define ID_VELOCITYVOLUME_COMPUTEALLINTERVALVELOCITIES 32835
#define ID_VELOCITYVOLUME_IMRCONVERTTIMEGRID 32839
#define ID_RAYTRACE                     32840
#define ID_RAYTRACE3D_PROPERTIES        32849
#define ID_GRIDS_OVERWRITENULL          32850
#define ID_PROJECT_NEW                  32851
#define ID_MODEL_SHOWRESI               32852
#define ID_WELLDATA_WELLDATATABLES      32854
#define ID_Menu                         32855
#define ID_HELP_DEMONSTRATIONVIDEOS     32856
#define ID_PROJECT_3DVIS                32857
#define ID_SEISMICDATA_OPENSEGYCONVERTER 32858
#define ID_VELOCITYVOLUME_IMRTEST       32859
#define ID_PROJECT_SAVEPROJECTREPORT    32860
#define ID_WELLDATA_DELETEWELL          32861
#define ID_WELLDATA_INTERPOLATEFAULTNULLPOLYGONS 32864
#define ID_Menu32865                    32865
#define ID_DEMONSTRATIONVIDEOS_FUNCTIONMODELLING 32866
#define ID_DEMONSTRATIONVIDEOS_FUNCTIONREFINEMENT 32867
#define ID_DEMONSTRATIONVIDEOS_FUNCTIONQUALITYCONTROL 32868
#define ID_DEMONSTRATIONVIDEOS_SAVINGWELLDATA 32869
#define ID_DEMONSTRATIONVIDEOS_GETTINGSTARTEDWITHRMSVELOCITIES 32870
#define ID_DEMONSTRATIONVIDEOS_PROCESSVELOCITYDATA 32871
#define ID_DEMONSTRATIONVIDEOS_RMSQUALITYCONTROL 32872
#define ID_DEMONSTRATIONVIDEOS_IMPORTINGSEGYDATA 32873
#define ID_DEMONSTRATIONVIDEOS_SAVINGGRIDS 32874
#define ID_DEMONSTRATIONVIDEOS_WELLDATAFORMAT 32875
#define ID_DEMONSTRATIONVIDEOS_IMRII    32876
#define ID_DEMONSTRATIONVIDEOS_3DVISUALISATION 32877
#define ID_DEMONSTRATIONVIDEOS_DEPTHMIGRATION 32878
#define ID_DEMONSTRATIONVIDEOS_DEPTHCONVERTSECONDARYGRID 32879
#define ID_DEMONSTRATIONVIDEOS_FUNCTIONRESIDUALCONTROLS 32880
#define ID_ShowWellDataTables           32881
#define ID_ShowWellDataTablesg          32882
#define ID_SHOWWELLDATATABLE            32883
#define ID_GRIDTOOLS_MATRIXSMOOTH       32884
#define ID_WELLDATA_EXPORTWELLDATAFILE  32885
#define LOG_NEWPROJ                     33000
#define LOG_NEWPROJ2                    33001
#define LOG_NEWPROJ_WL                  33002
#define LOG_CLOSEPROJ                   33004
#define LOG_OPENPROJ                    33005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32886
#define _APS_NEXT_CONTROL_VALUE         1375
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
